---
- name: Download {{ item }}
  get_url:
    url=https://downloads.wordpress.org/plugin/{{ item }}.zip
    dest=/tmp/{{ item }}.zip
    validate_certs=no
  with_items: "{{ plugins }}"

- name: Extract {{ item }}
  unarchive: src=/tmp/{{ item }}.zip dest={{ wp_path }}/wp-content/plugins copy=no
  with_items: "{{ plugins }}"

- name: Set permissions on plugins
  file:
    path: "{{ wp_path }}/wp-content/plugins"
    recurse: yes
    owner: www-data
    group: www-data
