---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - mysql-server
    - php-mysql
    - python-mysqldb

- name: Start mysql
  service: name=mysql state=started enabled=true

- name: Set root user password
  command: >
    mysql -u root --execute="SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{ mysql_root_password }}');"

- name: Create mysql user
  mysql_user:
    name={{ mysql_user }}
    password="{{ mysql_password }}"
    priv=*.*:ALL
    login_user=root
    login_password="{{ mysql_root_password }}"
